# Generated by Django 4.2.4 on 2023-09-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=63, verbose_name='Token')),
                ('name', models.CharField(max_length=63, verbose_name='Name')),
                ('about', models.TextField(max_length=255, verbose_name='About')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
            ],
        ),
    ]
