# Generated by Django 4.2.4 on 2023-09-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='about',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(max_length=63, unique=True, verbose_name='Token'),
        ),
    ]
