# Generated by Django 4.2.4 on 2023-09-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tg_id',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
