# Generated by Django 4.2.4 on 2023-09-03 19:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_alter_customuser_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
