version: '3.1'

services:

  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: tb
      POSTGRES_USER: tb
      PGDATA: /home/ilmix/docker/postgis
    ports:
      - 5455:5432
